name: n8n-workflow
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    expose:
      - "${PORT}"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${PORT}
      - N8N_PROTOCOL=${PROTOCOL}
      - N8N_USER_MANAGEMENT_DISABLED=true
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_PROXY_HOPS=1 # Hace falta si hay un proxy por delante
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.mkit-workflow.rule=Host(`${N8N_HOST}`)"
      - "traefik.http.routers.mkit-workflow.entrypoints=websecure"
      - "traefik.http.routers.mkit-workflow.tls=true"
      - "traefik.http.routers.mkit-workflow.tls.certresolver=letsencrypt"
      #- "traefik.http.routers.mkit-workflow=mkit-workflow"
      - "traefik.http.routers.mkit-workflow.service=mkit-workflow"
      - "traefik.http.services.mkit-workflow.loadbalancer.server.port=${PORT}"

volumes:
  n8n_data:

networks:
  traefik:
   external: true
